# Generated by Django 5.0.6 on 2024-06-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('ocupacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoVenta',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=255)),
                ('fono', models.CharField(max_length=255)),
                ('consulta', models.TextField()),
                ('boletin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField()),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageConfigPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.imagefolders')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('images_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.imageconfigportafolio')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTestimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonio', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('bajada_texto', models.TextField(blank=True, null=True)),
                ('parrafos', models.TextField(blank=True, null=True)),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='re_mirada.blogimagen')),
                ('lista', models.ManyToManyField(to='re_mirada.listaitem')),
            ],
        ),
        migrations.CreateModel(
            name='Cartablog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('bajada_titulo', models.CharField(max_length=255)),
                ('fechapub', models.DateField()),
                ('tag', models.CharField(max_length=255)),
                ('cita', models.TextField(blank=True, null=True)),
                ('secciones', models.ManyToManyField(to='re_mirada.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFoto',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('incluye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incluye', to='re_mirada.servicios')),
                ('no_incluye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_incluye', to='re_mirada.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahorros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(to='re_mirada.productocarrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.usuario')),
            ],
        ),
    ]
