# Generated by Django 5.0.6 on 2024-06-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='ahorros',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='precio_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='re_mirada.usuario'),
        ),
        migrations.CreateModel(
            name='ProductoPCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='re_mirada.carrito')),
                ('producto_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.productocarrito')),
            ],
        ),
    ]
