# Generated by Django 5.0.6 on 2024-06-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0002_remove_carrito_id_remove_carrito_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
