# Generated by Django 5.0.6 on 2024-06-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0003_alter_producto_imagen_url_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
