# Generated by Django 5.0.6 on 2024-06-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopcarrito',
            name='producto_carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.producto'),
        ),
        migrations.DeleteModel(
            name='ProductoCarrito',
        ),
    ]
