# Generated by Django 5.0.6 on 2024-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0005_alter_productopcarrito_producto_carrito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
