# Generated by Django 5.0.6 on 2024-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0006_rename_nombre_usuario_first_name_usuario_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
