# Generated by Django 5.0.6 on 2024-06-24 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0007_usuario_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.carrito')),
            ],
        ),
    ]
