# Generated by Django 5.0.6 on 2024-06-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0011_alter_pedido_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='re_mirada.carrito'),
        ),
    ]
