# Generated by Django 5.0.6 on 2024-06-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0012_remove_pedido_id_alter_pedido_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
