# Generated by Django 5.0.6 on 2024-06-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0013_alter_pedido_comuna_alter_pedido_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='re_mirada.carrito'),
        ),
    ]
