# Generated by Django 5.0.6 on 2024-06-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0014_alter_pedido_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.pedido')),
            ],
        ),
    ]
