# Generated by Django 5.0.6 on 2024-06-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0016_remove_pedidohistorico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidohistorico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.usuario'),
        ),
    ]
