# Generated by Django 5.0.6 on 2024-07-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0017_alter_pedidohistorico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.pedidohistorico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_mirada.producto')),
            ],
        ),
    ]
