# Generated by Django 5.0.6 on 2024-07-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_mirada', '0018_productospedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfoto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='planfoto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='planfoto',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='re_mirada.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planfoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
